### ISSUE TITLE
List of issues 

### ISSUE THREAD

**Issue by Simon-Stasovski** [Pavel-Sushko/Kiosk#11]
![image](https://user-images.githubusercontent.com/76963141/103809711-eb815380-5027-11eb-9818-2d4c62a6268c.png)

**Comment by Pavel-Sushko** [comment]
Please make sure that you Stop any active iterations of the code before modifying them. This issue has been closed as it is not related to a problem with the code.

**Comment by Pavel-Sushko** [comment]
Please make sure that you stop any active iterations of the code before modifying them. This issue has been closed as it is not related to a problem with the code.
